#!/bin/bash
export OS_PROJECT_DOMAIN_NAME=Default
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_NAME=Attack_Project
export OS_USERNAME=seed
export OS_PASSWORD=seedadmin
export OS_AUTH_URL=http://192.168.98.143:5000/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
